/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 pvc window.glb instanceall --transform 
Files: pvc window.glb [340.61KB] > /Users/led/Documents/react-three-next/public/pvc window-transformed.glb [28.81KB] (92%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Pvcw(props) {
  const { nodes, materials } = useGLTF('/pvc window-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Frame_01_2.geometry} material={nodes.Frame_01_2.material} position={[0, 0.304, 0]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.025} />
    </group>
  )
}

useGLTF.preload('/pvc window-transformed.glb')
