/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 pvc window.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Pvcw(props) {
  const { nodes, materials } = useGLTF('/pvc window.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.304, 0]} rotation={[Math.PI, 0, Math.PI]} scale={0.025}>
        <group position={[11.015, 0, 1.418]}>
          <group position={[-20.248, -1.6, 1.72]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Grip_01.geometry} material={nodes.Grip_01.material} position={[0.02, -0.937, -2.432]} rotation={[-Math.PI / 2, 0, Math.PI]} />
            <mesh geometry={nodes.Grip_02.geometry} material={nodes.Grip_02.material} />
          </group>
          <mesh geometry={nodes.Frame_02_2.geometry} material={nodes.Frame_02_2.material} position={[-11.015, 0, -0.93]} />
          <mesh geometry={nodes.Fused_Gaskets_01.geometry} material={nodes.Fused_Gaskets_01.material} position={[-11.023, -0.005, -1.7]} />
          <mesh geometry={nodes.Fused_Gaskets_02.geometry} material={nodes.Fused_Gaskets_02.material} position={[-11.023, -0.005, -0.373]} />
          <mesh geometry={nodes.Fused_Gaskets_03.geometry} material={nodes.Fused_Gaskets_03.material} position={[-11.015, 0, -0.314]} rotation={[Math.PI, 0, Math.PI]} />
          <mesh geometry={nodes.Hinge_01.geometry} material={nodes.Hinge_01.material} position={[0.001, 8.533, 0]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Hinge_02.geometry} material={nodes.Hinge_02.material} position={[0.001, -8.523, 0]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Lock_01_1.geometry} material={nodes.Lock_01_1.material} position={[-20.323, -6.779, -1.198]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} />
          <mesh geometry={nodes.Lock_01_2.geometry} material={nodes.Lock_01_2.material} position={[-20.249, -6.608, -1.197]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} />
          <mesh geometry={nodes.Lock_02_1.geometry} material={nodes.Lock_02_1.material} position={[-20.323, 6.433, -1.198]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} />
          <mesh geometry={nodes.Lock_02_2.geometry} material={nodes.Lock_02_2.material} position={[-20.249, 6.604, -1.197]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} />
          <mesh geometry={nodes.Lock_03.geometry} material={nodes.Lock_03.material} position={[-10.835, -0.882, -13.451]} rotation={[0, 0, -Math.PI]} />
          <mesh geometry={nodes.Objekt_01.geometry} material={nodes.Objekt_01.material} position={[-11.012, 0.001, -1.243]} />
          <mesh geometry={nodes.Objekt_02.geometry} material={nodes.Objekt_02.material} position={[-11.012, 0.001, -0.729]} />
          <mesh geometry={nodes.Thermal_Glass_01.geometry} material={nodes.Thermal_Glass_01.material} position={[-11.011, 0.006, -1.5]} />
          <mesh geometry={nodes.Thermal_Glass_02.geometry} material={nodes.Thermal_Glass_02.material} position={[-11.011, 0.006, -0.987]} />
          <mesh geometry={nodes.Thermal_Glass_03.geometry} material={nodes.Thermal_Glass_03.material} position={[-11.011, 0.006, -0.471]} />
        </group>
        <mesh geometry={nodes.Frame_01_2.geometry} material={nodes.Frame_01_2.material} />
        <mesh geometry={nodes.Fused_Gaskets_04.geometry} material={nodes.Fused_Gaskets_04.material} position={[0, 0.001, -0.71]} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.Lock_02.geometry} material={nodes.Lock_02.material} position={[-9.462, 6.604, 0.22]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Lock_02_1_2.geometry} material={nodes.Lock_02_1_2.material} position={[-9.462, -6.608, 0.22]} rotation={[Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/pvc window.glb')
