/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 windowmeshes.glb 
*/

import React, {useRef, useState} from 'react'
import {useGLTF, useAnimations, Edges, useSelect, useCursor} from '@react-three/drei'
import {FirstLevaControl, useControls} from "@/components/FirstLevaControl";

export function Windowmeshes(props) {
  const [selected, setSelected] = useState()

  const [shiny, setShiny] = useState(false)
  const [hovered, setHover] = useState(false)
  const selecteded = useSelect().map((sel) => sel.userData.store)
  const [store, materialProps] = useControls(selecteded, FirstLevaControl)
  const isSelected = !!selecteded.find((sel) => sel === store)
  const group = useRef()
  const {nodes, materials, animations} = useGLTF('/windowmeshes.glb')
  const {actions} = useAnimations(animations, group)

  useCursor(hovered)

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Mesh61" geometry={nodes.Mesh61.geometry} material={materials.Steel}
              position={[-11.348, -0.074, 30.383]} rotation={[Math.PI / 2, 0, 0]} scale={1}><Edges
          visible={isSelected} scale={1.1} renderOrder={1000}>
          <meshBasicMaterial transparent color='#333' depthTest={false}/>
        </Edges>
          <meshPhongMaterial color={shiny ? 0xff00ff : 0xffffff}/>
        </mesh>
        <mesh name="Mesh60" geometry={nodes.Mesh60.geometry} material={materials.Steel}
              position={[-11.348, -0.074, 30.383]} rotation={[Math.PI / 2, 0, 0]} scale={1}><Edges
          visible={isSelected} scale={1.1} renderOrder={1000}>
          <meshBasicMaterial transparent color='#333' depthTest={false}/>
        </Edges>
          <meshPhongMaterial color={shiny ? 0xff00ff : 0xffffff}/>
        </mesh>
        <mesh name="Mesh58" geometry={nodes.Mesh58.geometry} material={materials.Steel}
              position={[-11.348, -0.074, 30.383]} rotation={[Math.PI / 2, 0, 0]} scale={1}>
          <Edges visible={isSelected} scale={1.1} renderOrder={1000}>
            <meshBasicMaterial transparent color='#333' depthTest={false} />
          </Edges>
          <meshPhongMaterial color={shiny ? 0xff00ff : 0xffffff} />
        </mesh>
        <mesh name="Mesh57" geometry={nodes.Mesh57.geometry} material={materials.Steel}
              position={[-11.348, -0.074, 30.383]} rotation={[Math.PI / 2, 0, 0]} scale={1}>
          <Edges visible={isSelected} scale={1.1} renderOrder={1000}>
            <meshBasicMaterial transparent color='#333' depthTest={false} />
          </Edges>
          <meshPhongMaterial color={shiny ? 0xff00ff : 0xffffff} />
        </mesh>
        <mesh name="Mesh65" geometry={nodes.Mesh65.geometry} material={materials['02 - Default']}
              position={[-11.34, -0.074, 30.383]} rotation={[Math.PI / 2, 0, 0]} scale={1}>
          <Edges visible={isSelected} scale={1.1} renderOrder={1000}>
            <meshBasicMaterial transparent color='#333' depthTest={false} />
          </Edges>
          <meshPhongMaterial color={shiny ? 0xff00ff : 0xffffff} />
        </mesh>
        <mesh name="Mesh64" geometry={nodes.Mesh64.geometry} material={materials['02 - Default']}
              position={[-11.34, -0.074, 30.383]} rotation={[Math.PI / 2, 0, 0]} scale={1}>
          <Edges visible={isSelected} scale={1.1} renderOrder={1000}>
            <meshBasicMaterial transparent color='#333' depthTest={false} />
          </Edges>
          <meshPhongMaterial color={shiny ? 0xff00ff : 0xffffff} />
        </mesh>
        <mesh name="Mesh63" geometry={nodes.Mesh63.geometry} material={materials['01 - Default']}
              position={[-11.34, -0.074, 30.383]} rotation={[Math.PI / 2, 0, 0]} scale={1}>
          <Edges visible={isSelected} scale={1.1} renderOrder={1000}>
            <meshBasicMaterial transparent color='#333' depthTest={false} />
          </Edges>
          <meshPhongMaterial color={shiny ? 0xff00ff : 0xffffff} />
        </mesh>
        <mesh name="Mesh62" geometry={nodes.Mesh62.geometry} material={materials['01 - Default']}
              position={[-11.34, -0.074, 30.383]} rotation={[Math.PI / 2, 0, 0]} scale={1}>
          <Edges visible={isSelected} scale={1.1} renderOrder={1000}>
            <meshBasicMaterial transparent color='#333' depthTest={false} />
          </Edges>
          <meshPhongMaterial color={shiny ? 0xff00ff : 0xffffff} />
        </mesh>
        <mesh name="Mesh59" geometry={nodes.Mesh59.geometry} material={materials['01 - Default']}
              position={[-11.34, -0.074, 30.383]} rotation={[Math.PI / 2, 0, 0]} scale={1}>
          <Edges visible={isSelected} scale={1.1} renderOrder={1000}>
            <meshBasicMaterial transparent color='#333' depthTest={false} />
          </Edges>
          <meshPhongMaterial color={shiny ? 0xff00ff : 0xffffff} />
        </mesh>
        <mesh name="Mesh56" geometry={nodes.Mesh56.geometry} material={materials['01 - Default']}
              position={[-11.34, -0.074, 30.383]} rotation={[Math.PI / 2, 0, 0]} scale={1}>
          <Edges visible={isSelected} scale={1.1} renderOrder={1000}>
            <meshBasicMaterial transparent color='#333' depthTest={false} />
          </Edges>
          <meshPhongMaterial color={shiny ? 0xff00ff : 0xffffff} />
        </mesh>
        <mesh name="Mesh55" geometry={nodes.Mesh55.geometry} material={materials['09 - Default']}
              position={[-11.34, -0.074, 30.383]} rotation={[Math.PI / 2, 0, 0]} scale={1}>
          <Edges visible={isSelected} scale={1.1} renderOrder={1000}>
            <meshBasicMaterial transparent color='#333' depthTest={false} />
          </Edges>
          <meshPhongMaterial color={shiny ? 0xff00ff : 0xffffff} />
        </mesh>
        <mesh name="Mesh54" geometry={nodes.Mesh54.geometry} material={materials['09 - Default']}
              position={[-11.34, -0.074, 30.383]} rotation={[Math.PI / 2, 0, 0]} scale={1}>
          <Edges visible={isSelected} scale={1.1} renderOrder={1000}>
            <meshBasicMaterial transparent color='#333' depthTest={false} />
          </Edges>
          <meshPhongMaterial color={shiny ? 0xff00ff : 0xffffff} />
        </mesh>
        <mesh name="Mesh53" geometry={nodes.Mesh53.geometry} material={materials['02 - Default']}
              position={[-11.34, -0.074, 30.383]} rotation={[Math.PI / 2, 0, 0]} scale={1}>
          <Edges visible={isSelected} scale={1.1} renderOrder={1000}>
            <meshBasicMaterial transparent color='#333' depthTest={false} />
          </Edges>
          <meshPhongMaterial color={shiny ? 0xff00ff : 0xffffff} />
        </mesh>
        <mesh name="Mesh52" geometry={nodes.Mesh52.geometry} material={materials['02 - Default']}
              position={[-11.34, -0.074, 30.383]} rotation={[Math.PI / 2, 0, 0]} scale={1}>
          <Edges visible={isSelected} scale={1.1} renderOrder={1000}>
            <meshBasicMaterial transparent color='#333' depthTest={false} />
          </Edges>
          <meshPhongMaterial color={shiny ? 0xff00ff : 0xffffff} />
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/windowmeshes.glb')
